local AppleCheats = loadstring(game:HttpGet("https://raw.githubusercontent.com/Proxo123/applecheats-lib/main/AppleCheats.lua"))()

local Window = AppleCheats:CreateWindow({
	Title = "APPLE FORTNITE",
	Subtitle = "menu is only usable in game",
	Keybind = Enum.KeyCode.RightShift,
})

local Aimbot = Window:AddTab("Aimbot")
local Visuals = Window:AddTab("Visuals")
local Mods = Window:AddTab("Mods")
local Misc = Window:AddTab("Misc")

local Env = Visuals:AddColumn("Environment:")
Env:AddCheckbox("Loot", true)
Env:AddSlider("Loot Max Distance", 0, 1000, 120)
Env:AddSlider("Chest Max Distance", 0, 1000, 120)
Env:AddCheckbox("Vehicles", true)
Env:AddSlider("Vehicle Max Distance", 0, 1000, 240)
Env:AddCheckbox("Projectiles/Traps", true)

local Player = Visuals:AddColumn("Player:")
Player:AddCheckbox("Box", true)
Player:AddCheckbox("Name", true)
Player:AddCheckbox("Distance", true)
Player:AddCheckbox("Skeleton", true)
Player:AddCheckbox("Weapon/Active item", true)

local VisualMisc = Visuals:AddColumn("Misc:")
VisualMisc:AddCheckbox("Aimbot Indicators", true)
VisualMisc:AddCheckbox("Aimbot FOV", true)
VisualMisc:AddCheckbox("Crosshair", true)
VisualMisc:AddCheckbox("Visibility Check", true)
VisualMisc:AddCheckbox("Chams", true)
VisualMisc:AddCheckbox("Chams through walls", true)
VisualMisc:AddCheckbox("Self chams", true)
VisualMisc:AddCheckbox("Wireframe mode", true)
VisualMisc:AddSlider("Glowing intensity (%)", 0, 100, 5)

local Env2 = Aimbot:AddColumn("Environment:")
Env2:AddCheckbox("Loot (F1)", true)
Env2:AddCheckbox("Chests / ammo boxes (F2)", false)
Env2:AddCheckbox("Traps", true)
Env2:AddCheckbox("Rifts", true)
Env2:AddCheckbox("Supply drops", true)
Env2:AddCheckbox("Projectiles", true)
Env2:AddCheckbox("Vehicles", true)
Env2:AddLabel("Loot tier (PageUp/PageDown)")
Env2:AddCheckbox("Ultra common", true)
Env2:AddCheckbox("Common", true)
Env2:AddCheckbox("Uncommon", true)
Env2:AddCheckbox("Rare", true)
Env2:AddCheckbox("Epic", true)
Env2:AddSlider("Chests distance", 0, 1000, 150)
Env2:AddSlider("Loot distance", 0, 1000, 150)

local Player2 = Aimbot:AddColumn("Player:")
Player2:AddCheckbox("Box", true)
Player2:AddCheckbox("Name", true)
Player2:AddCheckbox("Skeleton", true)
Player2:AddCheckbox("Weapon/Active item", true)
Player2:AddCheckbox("Snaplines (F3)", true)
Player2:AddCheckbox("Snaplines visible only", true)
Player2:AddSlider("Snapline distance", 0, 500, 50)

local AimMisc = Aimbot:AddColumn("Misc:")
AimMisc:AddCheckbox("Aimbot FOV", true)
AimMisc:AddCheckbox("Aimbot indicators", true)
AimMisc:AddSlider("Overall ESP Distance", 0, 1000, 500)

local ModsCol = Mods:AddColumn(nil)
ModsCol:AddCheckbox("No weapon spread (F5)", true)
ModsCol:AddCheckbox("Instant reload", true)
ModsCol:AddCheckbox("BULLET TELEPORT (Sniper only)", true)
ModsCol:AddSlider("Camera FOV", 60, 120, 105)
ModsCol:AddSlider("Firing rate modifier", 1, 20, 7.5)

local MiscCol = Misc:AddColumn(nil)
MiscCol:AddButton("Unload Script", function()
	Window:Destroy()
end)
MiscCol:AddButton("Rejoin Server", function()
	game:GetService("Players").LocalPlayer:Kick("Rejoining...")
end)

AppleCheats:Notify("applecheats lib loaded", 4)
